# config.yaml
application:
  host: "127.0.0.1"
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "123456"
  db_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  token: "my-secret-token"
  timeout: 2000
